import React, { useState } from 'react';
import { ScanResultData } from '../types';
import { useTranslation } from '../i18n';
import { X, Copy, Check, Share2 } from 'lucide-react';

interface ShareModalProps {
  scan: ScanResultData;
  isOpen: boolean;
  onClose: () => void;
}

export const ShareModal: React.FC<ShareModalProps> = ({ scan, isOpen, onClose }) => {
  const { t } = useTranslation();
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const modelVersionsStr = Array.isArray(scan.model_versions)
    ? scan.model_versions.join(', ')
    : String(scan.model_versions || '');

  const reportText = `[Scam Shield Security Audit Report]
Analysis ID: ${scan.analysis_id || scan.scan_id}
Target: ${scan.target}
Risk Verdict: ${scan.risk_level} (Score: ${scan.risk_score}/100)
Uncertainty: ${scan.uncertainty}
Summary: ${scan.summary}

Top Reasons:
${scan.reasons.map((r, i) => `${i + 1}. ${r}`).join('\n')}

Active Detectors: ${modelVersionsStr}
Generated: ${new Date(scan.generated_at).toUTCString()}
Notice: Automated security advisory report generated by Scam Shield Platform.`;

  const handleCopy = () => {
    navigator.clipboard.writeText(reportText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/75 backdrop-blur-sm p-4">
      <div className="bg-[#0f172a] border border-[#334155] rounded-2xl max-w-lg w-full p-6 shadow-2xl relative space-y-4">
        <button
          onClick={onClose}
          className="absolute top-4 right-4 text-slate-400 hover:text-white p-1.5 rounded-lg hover:bg-[#1e293b] transition"
          aria-label={t('common.close')}
        >
          <X className="w-5 h-5" />
        </button>

        <div className="flex items-center gap-2.5">
          <div className="p-2 rounded-lg bg-cyan-950/80 border border-cyan-800/80 text-cyan-400">
            <Share2 className="w-5 h-5" />
          </div>
          <div>
            <h3 className="text-base font-bold text-white font-mono">{t('modals.exportTitle')}</h3>
            <span className="text-xs text-slate-400">{t('common.id')}: {scan.analysis_id || scan.scan_id}</span>
          </div>
        </div>

        <p className="text-xs text-slate-300 leading-relaxed">
          {t('modals.exportDesc')}
        </p>

        <textarea
          readOnly
          value={reportText}
          rows={9}
          className="w-full bg-[#070a12] border border-[#1e293b] rounded-xl p-3.5 text-xs font-mono text-slate-300 focus:outline-none select-all leading-relaxed"
        />

        <div className="flex items-center justify-end gap-3 pt-2">
          <button
            onClick={onClose}
            className="px-4 py-2 text-xs font-semibold text-slate-400 hover:text-white rounded-lg hover:bg-[#1e293b] transition"
          >
            {t('common.close')}
          </button>
          <button
            onClick={handleCopy}
            className="px-4 py-2 text-xs font-bold bg-cyan-600 hover:bg-cyan-500 text-white rounded-lg flex items-center gap-2 shadow transition"
          >
            {copied ? <Check className="w-4 h-4 text-emerald-300" /> : <Copy className="w-4 h-4" />}
            <span>{copied ? t('common.copied') : t('modals.btnCopyReport')}</span>
          </button>
        </div>
      </div>
    </div>
  );
};
